config/routes.rb
Rails.application.routes.draw do
  resources :programs
  get 'entrance/index'
  root 'entrance#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord

  def barebones_title
    title.sub(", #{degree_type}",'').sub(' Minor','').sub(' Graduate Certificate','').sub(' Undergraduate Certificate','').sub(', PhD', '').sub(', BSEd','')
  end

  def interpreted_degree
    case degree_type
    when ''
      then 'Minor'
    when 'CERG'
      then 'Graduate Certificate'
    when 'CERB'
      then 'Undergraduate Certificate'
    else
      degree_type
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entrance_controller.rb
class EntranceController < ApplicationController
  require 'open-uri'
  def index

  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all.order(:title)
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:title, :college_code, :department_code, :body, :program_type, :degree_type, :program_title, :schev_status, :college, :department, :joint_program, :code, :green_leaf_prog)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrance_helper.rb
module EntranceHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/entrance/index.html.erb
<h1>APInception</h1>
<h2>Real-time pull of program listings from catalog API, parsed to remove duplicates, linked to xml for program</h2>
<nav><%= link_to "Imported Program Data Demo", programs_path %></nav>
<iframe src="https://giphy.com/embed/9mmWez1yhWNXO" width="480" height="201" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
<div>
  <% url = 'https://catalog.gmu.edu/ribbit/?page=getprogram.rjs&code=*' %>
  <% response = Nokogiri::XML(open(url)) %>
  <% codes = [] %>
  <% response.xpath('programinfo/program').each do |program| %>
    <% code = program.attribute('code').value %>
    <% unless codes.include?(code) %>
      <% codes << code %>
      <%= content_tag :p, link_to(program.xpath('title').inner_html.html_safe, "https://catalog.gmu.edu/ribbit/?page=getprogram.rjs&code=#{code}") %>
    <% end %>
  <% end %>
  <%#= codes %>
</div>

app/views/entrance/show.xml.erb
<% url = 'https://catalog.gmu.edu/ribbit/?page=getprogram.rjs&code=#{params(:id)}' %>
<% response = Nokogiri::XML(open(url)) %>
<%= response %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apinception</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programs/_form.html.erb
<%= form_with(model: program, local: true) do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :college_code %>
    <%= form.text_field :college_code %>
  </div>

  <div class="field">
    <%= form.label :department_code %>
    <%= form.text_field :department_code %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :program_type %>
    <%= form.text_field :program_type %>
  </div>

  <div class="field">
    <%= form.label :degree_type %>
    <%= form.text_field :degree_type %>
  </div>

  <div class="field">
    <%= form.label :program_title %>
    <%= form.text_field :program_title %>
  </div>

  <div class="field">
    <%= form.label :schev_status %>
    <%= form.text_field :schev_status %>
  </div>

  <div class="field">
    <%= form.label :college %>
    <%= form.text_field :college %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :joint_program %>
    <%= form.text_field :joint_program %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :green_leaf_prog %>
    <%= form.text_field :green_leaf_prog %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programs</h1>

  <% @programs.group_by(&:barebones_title).each do |barebones_title, programs| %>
    <p><%= barebones_title %>, <% programs.each do |program| %><%= link_to program.interpreted_degree, program %><%= ', ' unless program == programs.last %><% end %></p>
  <% end %>

<br>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', programs_path %>

<p>
  <strong>Title:</strong>
  <%= @program.title %>
</p>

<p>
  <strong>College code:</strong>
  <%= @program.college_code %>
</p>

<p>
  <strong>College:</strong>
  <%= @program.college %>
</p>


<p>
  <strong>Department code:</strong>
  <%= @program.department_code %>
</p>
<p>
  <strong>Department:</strong>
  <%= @program.department %>
</p>

<p>
  <strong>Body:</strong>
  <%= @program.body %>
</p>

<p>
  <strong>Program type:</strong>
  <%= @program.program_type %>
</p>

<p>
  <strong>Degree type:</strong>
  <%= @program.degree_type %>
</p>

<p>
  <strong>Program title:</strong>
  <%= @program.program_title %>
</p>

<p>
  <strong>Schev status:</strong>
  <%= @program.schev_status %>
</p>



<p>
  <strong>Joint program:</strong>
  <%= @program.joint_program %>
</p>

<p>
  <strong>Code:</strong>
  <%= @program.code %>
</p>

<p>
  <strong>Green leaf prog:</strong>
  <%= @program.green_leaf_prog %>
</p>